function [ddx,ddy] = autoGen_pointMassDynamics(ux,uy,m,g)
%AUTOGEN_POINTMASSDYNAMICS
%    [DDX,DDY] = AUTOGEN_POINTMASSDYNAMICS(UX,UY,M,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    06-May-2020 21:08:55

t2 = 1.0./m;
ddx = t2.*ux;
if nargout > 1
    ddy = t2.*(uy-g.*m);
end
